# Site settings
title: ACORD/Stellarios
description: Robotics & Software by ACORD
keywords: Robotics, Software, Development
author: wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
